/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--dos-bg-rgb) / <alpha-value>)',
        bgPure: 'rgb(var(--dos-bg-pure-rgb) / <alpha-value>)',
        'bg-pure': 'rgb(var(--dos-bg-pure-rgb) / <alpha-value>)',
        panel: 'rgb(var(--dos-panel-rgb) / <alpha-value>)',
        panelSoft: 'rgb(var(--dos-panel-soft-rgb) / <alpha-value>)',
        'panel-soft': 'rgb(var(--dos-panel-soft-rgb) / <alpha-value>)',
        border: 'rgb(var(--dos-border-rgb) / <alpha-value>)',
        accent: 'rgb(var(--dos-accent-rgb) / <alpha-value>)',
        text: 'rgb(var(--dos-text-rgb) / <alpha-value>)',
        textMuted: 'rgb(var(--dos-text-muted-rgb) / <alpha-value>)',
        'text-muted': 'rgb(var(--dos-text-muted-rgb) / <alpha-value>)',
        dos: {
          bg: 'rgb(var(--dos-bg-rgb) / <alpha-value>)',
          bgPure: 'rgb(var(--dos-bg-pure-rgb) / <alpha-value>)',
          'bg-pure': 'rgb(var(--dos-bg-pure-rgb) / <alpha-value>)',
          text: 'rgb(var(--dos-text-rgb) / <alpha-value>)',
          textMuted: 'rgb(var(--dos-text-muted-rgb) / <alpha-value>)',
          'text-muted': 'rgb(var(--dos-text-muted-rgb) / <alpha-value>)',
          panel: 'rgb(var(--dos-panel-rgb) / <alpha-value>)',
          panelSoft: 'rgb(var(--dos-panel-soft-rgb) / <alpha-value>)',
          'panel-soft': 'rgb(var(--dos-panel-soft-rgb) / <alpha-value>)',
          border: 'rgb(var(--dos-border-rgb) / <alpha-value>)',
          sig: {
            warning: 'rgb(var(--dos-sig-warning-rgb) / <alpha-value>)',
            trust: 'rgb(var(--dos-sig-trust-rgb) / <alpha-value>)',
            drift: 'rgb(var(--dos-sig-drift-rgb) / <alpha-value>)',
            runtime: 'rgb(var(--dos-sig-runtime-rgb) / <alpha-value>)',
            continuity: 'rgb(var(--dos-sig-continuity-rgb) / <alpha-value>)',
          }
        }
      },
      boxShadow: {
        panel: '0 0 0 1px rgba(255,255,255,0.04), 0 8px 28px rgba(0,0,0,0.35)',
        m6tier1: 'var(--m6-tier1-shadow)',
      },
      opacity: {
        8: '0.08',
        12: '0.12',
        14: '0.14',
        16: '0.16',
        18: '0.18',
        22: '0.22',
        24: '0.24',
        26: '0.26',
        28: '0.28',
        34: '0.34',
        35: '0.35',
        42: '0.42',
        44: '0.44',
        52: '0.52',
        54: '0.54',
        58: '0.58',
        62: '0.62',
        64: '0.64',
        66: '0.66',
        68: '0.68',
        72: '0.72',
        76: '0.76',
        78: '0.78',
        82: '0.82',
        85: '0.85',
        86: '0.86',
        88: '0.88',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
};
